### PR TITLE
feat: bump vulnz-nvd-mirror version to 7.0.2

### PR DESCRIPTION
**Pull request by okgolove**
remove predefined JAVA_OPT memory allocation setting (ref: https://github.com/jeremylong/Open-Vulnerability-Project/pull/224)

### CODE REVIEW

**Comment by EugenMayer** [comment]
Thank you. Please revert the Java option removal, other than that it looks good already

**Comment by EugenMayer** [comment]
Since i want to upgrade vulnz, i would love to push this forward. Could you remove the changes i asked for so we can merge this one? Thanks!

**Comment by okgolove** [comment]
Hello @EugenMayer 
> Please revert the Java option removal
Could you explain a bit please? This options is not needed, Java now understands cgroup natively

**Comment by EugenMayer** [comment]
Fair point! so you refer to using https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container via the chart https://truecharts.org/common/resources/#resourceslimitsmemory to limit the memory of the java process. 

Beside this is not the same as defining the mean heap, i think you make a good point here.

I would still suggest adding limits to this charts by default (due to the nature of the actual application itself). Are you in on just adding resource limits in the same ballpark (that could be changed by anyone later one via the values)?

**Comment by okgolove** [comment]
Do I understand right you are suggest adding default memory limit to `resources` block, don't you?

**Comment by EugenMayer** [comment]
Yes, this was the suggestion

**Comment by EugenMayer** [comment]
Thank you!

**Review by EugenMayer — APPROVED** [review]

**Pull request merged**
