### PR TITLE
bugfix: mount pvc with mirror group id

### PR DESCRIPTION
**Pull request by okgolove**
By default 568 GID is used which causes error:

```java
Unable to write cached data: /usr/local/apache2/htdocs/nvdcve-2012.json.gz
io.github.jeremylong.vulnz.cli.cache.CacheException: Unable to write cached data: /usr/local/apache2/htdocs/nvdcve-2012.json.gz
        at io.github.jeremylong.vulnz.cli.commands.CveCommand.processRequest(CveCommand.java:330)
        at io.github.jeremylong.vulnz.cli.commands.CveCommand.timedCall(CveCommand.java:229)
        at io.github.jeremylong.vulnz.cli.commands.TimedCommand.call(TimedCommand.java:36)
        at io.github.jeremylong.vulnz.cli.commands.TimedCommand.call(TimedCommand.java:25)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at io.github.jeremylong.vulnz.cli.Application.run(Application.java:73)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.lambda$callRunners$2(SpringApplication.java:749)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
        at io.github.jeremylong.vulnz.cli.Application.main(Application.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.io.FileNotFoundException: /usr/local/apache2/htdocs/nvdcve-2012.json.gz (Permission denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at io.github.jeremylong.vulnz.cli.commands.CveCommand.processRequest(CveCommand.java:323)
        ... 35 common frames omitted
```

### CODE REVIEW

**Comment by EugenMayer** [comment]
How is that a general chart issue? Seems like a local issue you have, which you can fix by adding 

```
  pod:
    fsGroup: 101
```

to your deployment.

**Comment by okgolove** [comment]
Shouldn't chart work properly by default without adding extra values?
apche htdocs dir has group 568 without this adjustment, meanwhile `mirror.sh` is run under `mirror` user which has 101 gid.

**Comment by EugenMayer** [comment]
@okgolove for sure the chart should work out of the box, i'am just not sure why this is failing for you but not e..g. or for others - wouldnt that be a general issue?

What is your deployment `values.yml` in general?

**Comment by okgolove** [comment]
values.yaml:
```yaml
persistence:
  mirror:
    enabled: true
    size: 10Gi
workload:
  main:
    podSpec:
      containers:
        main:
          resources:
            limits:
              cpu: '3'
              memory: 4Gi
            requests:
              cpu: 10m
              memory: 50Mi
          env:
            NVD_API_KEY:
              secretKeyRef:
                name: nvd-api-key
                key: NVD_API_KEY
                expandObjectName: false
```

**Comment by EugenMayer** [comment]
I see, we run under 101 in the container, while we enforce 568 with the pod security. I assume we will need more fixes

```yaml
securityContext:
  container:
    PUID: 100
    runAsUser: 100
    runAsGroup: 101

  pod:
    fsGroup: 101
```

More under https://truecharts.org/common/securitycontext/ - what are your thoughts?

**Comment by okgolove** [comment]
As far as I understand running pod as root itself is ok ([httpd base image](https://github.com/jeremylong/Open-Vulnerability-Project/blob/main/vulnz/Dockerfile#L1) which is used as vulnz base image uses root by default). But supervisord runs `mirror.sh` script as [mirror user](https://github.com/jeremylong/Open-Vulnerability-Project/blob/main/vulnz/src/docker/supervisor/supervisord.conf#L61). So, we shouldn't to run main process as `mirror` user.

**Comment by EugenMayer** [comment]
you are right, we run as root so that supervisor can de-escalate privileges. With this, i think you a right on point with your PR, all we do is fsGroup privileges to match the user we run mirror with and that's it.

Thank you for elaborating and explaining, very appritiated!

**Comment by EugenMayer** [comment]
Could you add your changes for the target release of 0.4.0 (this could be a breaking change) to the changelog at https://github.com/EugenMayer/helm-charts/blob/main/charts/vulnz-nvd-mirror/CHANGELOG.md

and then we are good to go!

**Comment by EugenMayer** [comment]
@okgolove any chance you finish this PR soonish? Thanks

**Comment by okgolove** [comment]
Did I get right updating CHANGELOG in enough?

**Review by EugenMayer — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
