### PR TITLE
Added sideCars to Rundeck helm chart deployment template

### PR DESCRIPTION
**Pull request by jgtr-blis**
As per issue https://github.com/EugenMayer/helm-charts/issues/50 the readme for the Rundeck helm chart currently states that the sideCars value can be used to run additional containers in the Rundeck pod, however although it is mentioned in the chart readme and a commented out example exists in the [values](https://github.com/EugenMayer/helm-charts/blob/main/charts/rundeck/values.yaml#L200) file it isn't actually applied by the deployment template.

This change therefore re-adds the sideCars into the Rundeck deployment template to allow sidecar containers (such as the rundeck-exporter for monitoring purposes) to be deployed via the Rundeck chart.

### CODE REVIEW

**Comment by EugenMayer** [comment]
Thanks for the PR and sorry for being so late with the review. Could you test-drive this for your use case?

**Comment by jgtr-blis** [comment]
Apologies for the delay on getting back to you - I've actually been away for a while and I'm just catching up on things. 

Just to clarify what you mean by "test-drive" are you referring to adding an example to the values-test.yaml or something else?

**Comment by EugenMayer** [comment]
Did you deploy this onto a cluster and got it working - an manual e2e test so to say

**Comment by jgtr-blis** [comment]
Yes I've been running this in our environment since I raised the PR

**Comment by EugenMayer** [comment]
I see. The only thing we need to ensure is that we also can deploy without sidecar, which i would say can be seen in the code already. 

LGTM

**Comment by jgtr-blis** [comment]
I've spun up a Rundeck instance in MicroK8S with this version of the chart and the sidecar configuration set as:
```
sideCars:
  ""
```
which worked as expected and also with the config I'm using in prod which includes a sidecar and that also works so it should be good to go.

**Review by EugenMayer — APPROVED** [review]

**Comment by EugenMayer** [comment]
Thank you a lot for your patience @jgtr-blis 

Thank you for the contribution

**Comment by jgtr-blis** [comment]
Glad to have helped @EugenMayer. Is there a reason the new Rundeck 1.11.0 chart isn't showing in the helm repo now?
https://eugenmayer.github.io/helm-charts/

It looks as though you ran a job to update the index.yaml, however when I view the contents of the live file it's missing:
https://github.com/EugenMayer/helm-charts/commit/0613aac9ad44b5ab94a79e0902e011c469944471

**Comment by EugenMayer** [comment]
@jgtr-blis i have issue releasing the chart right now https://github.com/helm/chart-releaser/issues/379

This blocks me from getting the chart up and running. You can use the chart from the repo or release it to your custom chart museum.

Kind of stuck here right now

**Comment by EugenMayer** [comment]
opened #53

**Comment by jgtr-blis** [comment]
Thanks for the update. 

Sorry to hear you are having issues with the chart-releaser - I thought I would mention it in case you weren't aware of the issue, however it sounds like you are on top of it.

**Comment by EugenMayer** [comment]
@jgtr-blis it is fixed now, should be available in abou 20 mins via artifactory

**Pull request merged**
